export const servicesAPI = [
  {
    id: 1,
    name: "Weather Alerts",
    category: "Weather",
    cities: ["Kathmandu", "Pokhara", "Delhi", "London"],
    price: 10,
    rating: 4.5,
  },
  {
    id: 2,
    name: "Flood Warning System",
    category: "Safety",
    cities: ["Lalitpur", "Mumbai", "Chennai"],
    price: 15,
    rating: 4.7,
  },
  {
    id: 3,
    name: "Travel Guide",
    category: "Travel",
    cities: ["Kathmandu", "Paris", "Tokyo", "Sydney"],
    price: 20,
    rating: 4.3,
  },
  {
    id: 4,
    name: "Hotel Booking",
    category: "Travel",
    cities: ["New York", "London", "Paris", "Tokyo"],
    price: 25,
    rating: 4.6,
  },
  {
    id: 5,
    name: "Food Delivery",
    category: "Food",
    cities: ["Kathmandu", "Delhi", "Mumbai", "New York"],
    price: 5,
    rating: 4.2,
  },
  {
    id: 6,
    name: "Farming Advice",
    category: "Agriculture",
    cities: ["Pokhara", "Biratnagar"],
    price: 8,
    rating: 4.4,
  },
  {
    id: 7,
    name: "Emergency Support",
    category: "Safety",
    cities: ["Delhi", "Chicago", "Berlin"],
    price: 18,
    rating: 4.8,
  },
  {
    id: 8,
    name: "Ride Sharing",
    category: "Transport",
    cities: ["Kathmandu", "Bangalore", "Los Angeles"],
    price: 12,
    rating: 4.1,
  },
  {
    id: 9,
    name: "Courier Service",
    category: "Logistics",
    cities: ["London", "Berlin", "Beijing"],
    price: 9,
    rating: 4.0,
  },
  {
    id: 10,
    name: "Event Planning",
    category: "Lifestyle",
    cities: ["Paris", "Sydney", "New York"],
    price: 30,
    rating: 4.6,
  },

  // EXTRA (to make it feel big)
  {
    id: 11,
    name: "Water Delivery",
    category: "Utility",
    cities: ["Delhi", "Chennai", "Kathmandu"],
    price: 6,
    rating: 4.3,
  },
  {
    id: 12,
    name: "Electric Repair",
    category: "Home Service",
    cities: ["Pokhara", "Mumbai", "Berlin"],
    price: 14,
    rating: 4.2,
  },
  {
    id: 13,
    name: "AC Installation",
    category: "Home Service",
    cities: ["Delhi", "Los Angeles"],
    price: 22,
    rating: 4.5,
  },
  {
    id: 14,
    name: "Cleaning Service",
    category: "Home Service",
    cities: ["London", "New York", "Kathmandu"],
    price: 11,
    rating: 4.4,
  },
  {
    id: 15,
    name: "Fitness Training",
    category: "Health",
    cities: ["Sydney", "Tokyo", "Bangalore"],
    price: 19,
    rating: 4.7,
  },
];
