
export const weatherAPI = [
  {
    id: 1,
    city: "Kathmandu",
    country: "Nepal",
    temp: 22,
    condition: "Cloudy",
    humidity: 60,
    wind: 10,
  },
  {
    id: 2,
    city: "Pokhara",
    country: "Nepal",
    temp: 25,
    condition: "Sunny",
    humidity: 55,
    wind: 8,
  },
  {
    id: 3,
    city: "Biratnagar",
    country: "Nepal",
    temp: 30,
    condition: "Hot",
    humidity: 70,
    wind: 12,
  },
  {
    id: 4,
    city: "Lalitpur",
    country: "Nepal",
    temp: 21,
    condition: "Rainy",
    humidity: 80,
    wind: 15,
  },
  {
    id: 5,
    city: "Bhaktapur",
    country: "Nepal",
    temp: 20,
    condition: "Cloudy",
    humidity: 65,
    wind: 9,
  },
  {
    id: 6,
    city: "Delhi",
    country: "India",
    temp: 35,
    condition: "Hot",
    humidity: 40,
    wind: 14,
  },
  {
    id: 7,
    city: "Mumbai",
    country: "India",
    temp: 32,
    condition: "Humid",
    humidity: 85,
    wind: 11,
  },
  {
    id: 8,
    city: "Bangalore",
    country: "India",
    temp: 27,
    condition: "Pleasant",
    humidity: 60,
    wind: 7,
  },
  {
    id: 9,
    city: "Chennai",
    country: "India",
    temp: 34,
    condition: "Sunny",
    humidity: 75,
    wind: 13,
  },
  {
    id: 10,
    city: "New York",
    country: "USA",
    temp: 18,
    condition: "Windy",
    humidity: 50,
    wind: 20,
  },
  {
    id: 11,
    city: "Los Angeles",
    country: "USA",
    temp: 26,
    condition: "Sunny",
    humidity: 45,
    wind: 6,
  },
  {
    id: 12,
    city: "Chicago",
    country: "USA",
    temp: 15,
    condition: "Cold",
    humidity: 55,
    wind: 18,
  },
  {
    id: 13,
    city: "London",
    country: "UK",
    temp: 16,
    condition: "Rainy",
    humidity: 75,
    wind: 17,
  },
  {
    id: 14,
    city: "Paris",
    country: "France",
    temp: 19,
    condition: "Cloudy",
    humidity: 65,
    wind: 10,
  },
  {
    id: 15,
    city: "Berlin",
    country: "Germany",
    temp: 17,
    condition: "Foggy",
    humidity: 70,
    wind: 12,
  },
  {
    id: 16,
    city: "Tokyo",
    country: "Japan",
    temp: 23,
    condition: "Clear",
    humidity: 58,
    wind: 9,
  },
  {
    id: 17,
    city: "Seoul",
    country: "South Korea",
    temp: 21,
    condition: "Windy",
    humidity: 62,
    wind: 14,
  },
  {
    id: 18,
    city: "Beijing",
    country: "China",
    temp: 28,
    condition: "Smoggy",
    humidity: 68,
    wind: 16,
  },
  {
    id: 19,
    city: "Sydney",
    country: "Australia",
    temp: 24,
    condition: "Sunny",
    humidity: 50,
    wind: 8,
  },
  {
    id: 20,
    city: "Melbourne",
    country: "Australia",
    temp: 20,
    condition: "Rainy",
    humidity: 72,
    wind: 15,
  },
];
